# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Contributors to Eclipse OpenSOVD (see CONTRIBUTORS)
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0

version = 1

# declares copyright and license metadata for files that can't easily contain license headers themselves.
[[annotations]]
path = [
  "LICENSE",
  "NOTICE",
  "CONTRIBUTORS",
  "LICENSES/**.txt",
  "**/.env.example",
]
SPDX-FileCopyrightText = "The Contributors to Eclipse OpenSOVD (see CONTRIBUTORS)"
SPDX-License-Identifier = "Apache-2.0"
