# Copyright (c) 2025-2026 The Contributors to Eclipse OpenSOVD (see CONTRIBUTORS)
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0

name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  format_and_clippy_nightly_toolchain:
    concurrency:
      group: format_and_clippy_nightly_toolchain-${{ github.ref }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - toolchain: nightly-2025-07-14
            allow-failure: false
          - toolchain: nightly
            allow-failure: true
    continue-on-error: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy, rustfmt
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ matrix.toolchain }}
      - name: Formating - check for long lines
        run: cargo fmt -- --check --config error_on_unformatted=true,error_on_line_overflow=true,format_strings=true
      - name: Formatting - check import order
        run: cargo fmt -- --check --config group_imports=StdExternalCrate
      - name: Formatting - check imports granularity
        run: cargo fmt -- --check --config imports_granularity=Crate
      - name: Formatting - check hex literals
        run: cargo fmt -- --check --config hex_literal_case=Upper
      - name: Clippy
        uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-check'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clippy_flags: --locked --all-targets --features integration-tests ${{ matrix.allow-failure == false && '-- -D warnings' || '' }}
          filter_mode: 'nofilter'
          fail_on_error: ${{ !matrix.allow-failure }}

  features:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "--cfg tokio_unstable -L /usr/local/lib"
      PKG_CONFIG_PATH: "/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-07-14
          components: clippy
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          # The action queries the GitHub API to fetch releases data,
          # to avoid rate limiting, passing the default token.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup DLT
        uses: eclipse-opensovd/dlt-tracing-lib/.github/actions/setup-dlt@main
      - name: Clippy
        run: cargo clippy --locked --all-targets --all-features -- -D warnings
      - name: Build all features
        run: cargo build --locked --verbose --all-features
      - name: Build minimal features
        run: cargo build --locked --verbose --no-default-features
      - name: Build minimal CDA only
        # Building CDA only makes sure that optional dependencies
        # from within the workspace are properly marked as optional and guarded
        # with cfg flags.
        run: cargo build --locked --verbose --no-default-features --package opensovd-cda

  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.88.0
          components: clippy, rustfmt
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Install cargo-deny
        run: cargo install --locked --version 0.18.9 cargo-deny
      - name: Install taplo toml toolkit
        run: cargo install --locked --version 0.10.0 taplo-cli
      - name: check fmt
        run: cargo fmt --all -- --check
      - name: check toml fmt
        run: taplo fmt --check --diff
      - name: Run Clippy
        run: cargo clippy --locked --all-targets -- -D warnings
      - name: Build
        run: cargo build --locked --verbose
      - name: Check licenses
        run: cargo deny check licenses
      - name: Check advisories
        run: cargo deny check advisories
      - name: Check allowed sources
        run: cargo deny check sources
      - name: Check banned practises
        run: cargo deny check bans
      # In order to utilize caching, the docker images need to be built in the github action.
      - name: Build CDA docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: testcontainer/cda/Dockerfile
          push: false
          tags: ghcr.io/${{ github.repository }}/opensovd-cda:latest
          load: true
          cache-from: |
            type=gha,scope=cda-cargo-${{ github.ref_name }}
            type=gha,scope=cda-cargo-main
            type=gha,scope=cda-sccache-${{ github.ref_name }}
            type=gha,scope=cda-sccache-main
          cache-to: |
            type=gha,mode=max,scope=cda-cargo-${{ github.ref_name }}
            type=gha,mode=max,scope=cda-sccache-${{ github.ref_name }}
      - name: Build ECU Sim docker image
        uses: docker/build-push-action@v5
        with:
          context: testcontainer/ecu-sim/
          file: testcontainer/ecu-sim/docker/Dockerfile
          push: false
          tags: ghcr.io/${{ github.repository }}/ecu-sim:latest
          load: true
          cache-from: |
            type=gha,scope=ecu-sim-gradle-${{ github.ref_name }}
            type=gha,scope=ecu-sim-gradle-main
          cache-to: |
            type=gha,mode=max,scope=ecu-sim-gradle-${{ github.ref_name }}
      - name: Run tests
        env:
          CACHE_REGISTRY: ghcr.io/${{ github.repository }}
        run: cargo test --locked --features integration-tests -- --show-output

  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.88.0
          components: clippy, rustfmt
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Setup OpenSSL (Windows) Environment
        run: |
          echo "OPENSSL_DIR=$env:OPENSSL_DIR" >> $env:GITHUB_ENV
          echo "OPENSSL_LIB_DIR=$env:OPENSSL_DIR\lib\VC\$env:RUNNER_ARCH\MD" >> $env:GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=$env:OPENSSL_DIR\include" >> $env:GITHUB_ENV
        env:
          OPENSSL_DIR: C:\Program Files\OpenSSL
      - name: Build
        run: cargo build --locked --verbose
      - name: Test
        run: cargo test --locked -- --show-output

  check_copyright_headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check License Headers
        uses: apache/skywalking-eyes/header@v0.7.0
        with:
          config: .licenserc.yaml
